---
###
az-configuration:
- name: us-east-1a
- name: us-east-1b
- name: us-east-1c
web-lb-security-group:
- sg-06f4377429041345e
- sg-0b91a42ebf9fe6cf5
web-lb-target-group: 
- dev-web-tg-443
- dev-web-tg-80
bosh-vms-ssh-key-name: pcf-opsman-key-terra
default-region: us-east-1
bosh-vm-security-group: sg-0f9fd8575e4180dce
singleton-network-name: pcf-infra
singleton-az: us-east-1a
az1: us-east-1a
az2: us-east-1b
az3: us-east-1c
dns: 10.65.0.2
pcf-infra-network: pcf-infra 
pcf-infra-1-subnet-id: subnet-089f3a6265f9cae77
pcf-infra-1-subnet-cidr: 10.65.16.0/28
pcf-infra-1-subnet-gateway: 10.65.16.1
pcf-infra-1-reserved-ips: 10.65.16.0-10.65.16.11
pcf-infra-2-subnet-id: subnet-057669e000519123f
pcf-infra-2-subnet-cidr: 10.65.16.16/28
pcf-infra-2-subnet-gateway: 10.65.16.17
pcf-infra-2-reserved-ips: 10.65.16.16-10.65.16.20
pcf-infra-3-subnet-id: subnet-01f1705b3a463e418
pcf-infra-3-subnet-cidr: 10.65.16.32/28
pcf-infra-3-subnet-gateway: 10.65.16.33
pcf-infra-3-reserved-ips: 10.65.16.32-10.65.16.36
pcf-pas-network: pcf-pas
pcf-pas-1-subnet-id: subnet-02b8edffc34318ef4
pcf-pas-1-subnet-cidr: 10.65.4.0/24
pcf-pas-1-subnet-gateway: 10.65.4.1 
pcf-pas-1-reserved-ips: 10.65.4.0-10.65.4.4
pcf-pas-2-subnet-id: subnet-0d9147e5b4dc3fe37
pcf-pas-2-subnet-cidr: 10.65.5.0/24
pcf-pas-2-subnet-gateway: 10.65.5.1
pcf-pas-2-reserved-ips: 10.65.5.0-10.65.5.4
pcf-pas-3-subnet-id: subnet-05938845cd802df25
pcf-pas-3-subnet-cidr: 10.65.6.0/24
pcf-pas-3-subnet-gateway: 10.65.6.1
pcf-pas-3-reserved-ips: 10.65.6.0-10.65.6.4
pcf-service-network: pcf-service
pcf-services-1-subnet-id: subnet-004dd12bde1425c72
pcf-services-1-subnet-cidr: 10.65.8.0/24
pcf-services-1-subnet-gateway: 10.65.8.1
pcf-services-1-reserved-ips: 10.65.8.0-10.65.8.4
pcf-services-2-subnet-id: subnet-025e45125c9163db5
pcf-services-2-subnet-cidr: 10.65.9.0/24
pcf-services-2-subnet-gateway: 10.65.9.1
pcf-services-2-reserved-ips: 10.65.9.0-10.65.9.4
pcf-services-3-subnet-id: subnet-0d0f625e36d826ed4
pcf-services-3-subnet-cidr: 10.65.10.0/24
pcf-services-3-subnet-gateway: 10.65.10.1
pcf-services-3-reserved-ips: 10.65.10.0-10.65.10.4
pcf-ondemand-network: pcf-ondemand
pcf-ondemand-1-subnet-id: subnet-0e96106717651928d
pcf-ondemand-1-subnet-cidr: 10.65.12.0/24
pcf-ondemand-1-subnet-gateway: 10.65.12.1
pcf-ondemand-1-reserved-ips: 10.65.12.0-10.65.12.4
pcf-ondemand-2-subnet-id: subnet-058ae6e58a277d574
pcf-ondemand-2-subnet-cidr: 10.65.13.0/24
pcf-ondemand-2-subnet-gateway: 10.65.13.1
pcf-ondemand-2-reserved-ips: 10.65.13.0-10.65.13.4
pcf-ondemand-3-subnet-id: subnet-0ada3e15c94afda18
pcf-ondemand-3-subnet-cidr: 10.65.14.0/24
pcf-ondemand-3-subnet-gateway: 10.65.14.1
pcf-ondemand-3-reserved-ips: 10.65.14.0-10.65.14.4
director-external-db-host: dev-bosh.cpd89iiyzhwi.us-east-1.rds.amazonaws.com
director-external-db-user: admin
ntp-servers: 0.amazon.pool.ntp.org, 1.amazon.pool.ntp.org, 2.amazon.pool.ntp.org, 3.amazon.pool.ntp.org
director-s3-bucket-name: abc123xyz-pcf-ops-manager-bucket
director-s3-endpoint: https://s3.us-east-1.amazonaws.com
director-s3-region: us-east-1
