---
opsman-configuration:
  aws:
    region: "us-east-1"
    vm_name: "ops-manager-sandbox"
    vpc_subnet_id: "subnet-014227580f6a21566"
    security_group_id: "sg-00aeddfd8354ce3de"
    key_pair_name: "pcf-opsman-key-terra"
    private_ip: "10.65.16.10"
    access_key_id: ((access-key-id))
    secret_access_key: ((secret-access-key))
    vm_name: "ops-manager-vm"    # default - ops-manager-vm
    boot_disk_size: 100        # default - 200 (GB)
    instance_type: "m5.large"    # default - m5.large
    use_instance_profile: false # DEPRECATED - will use instance profile for
    iam_instance_profile_name: env_ops_manager
# Note that because this config contains no secrets
# and is already written to a foundation-specific filepath,
# it need not be interpolated.

