---
sys-domain: sys.sandbox.cps-prft.com
app-domain: apps.sandbox.cps-prft.com
mysql-monit-email: vkartheek.ky1311@gmail.com
credhub-user: admin
credhub-encrypt-key-user: admin
pas-network: pcf-pas
az-configuration:
- name: us-east-1a
- name: us-east-1b
- name: us-east-1c
singleton-az: us-east-1a
credhub_internal_provider_key_name: sandboxcredhubtestkey
buildpack-bucket: abc123xyz-pcf-buildpacks-bucket
droplet-bucket: abc123xyz-pcf-droplets-bucket
package-bucket: abc123xyz-pcf-packages-bucket
resource-bucket: abc123xyz-pcf-resources-bucket
backup-buildpack-bucket: sandbox-backup-buildpack-bucket-bcbsma-n
backup-droplet-bucket: sandbox-backup-droplet-bucket-bcbsma-n
backup-package-bucket: sandbox-backup-package-bucket-bcbsma-n
buckets-s3-endpoint: https://s3.us-east-1.amazonaws.com
buckets-s3-region: us-east-1
elb-target-gp-web:
- alb:sandbox-web-tg-443
- alb:sandbox-web-tg-443
elb-target-gp-ssh:
- alb:sandbox-ssh-tg
elb-target-gp-tcp:
- alb:sandbox-tcp-tg-1024
- alb:sandbox-tcp-tg-1025
- alb:sandbox-tcp-tg-1026
- alb:sandbox-tcp-tg-1027
- alb:sandbox-tcp-tg-1028
- alb:sandbox-tcp-tg-1029
- alb:sandbox-tcp-tg-1030
- alb:sandbox-tcp-tg-1031
- alb:sandbox-tcp-tg-1032
- alb:sandbox-tcp-tg-1033
elb-web-sg:
- sg-00aa8fbe578f6c382
elb-ssh-sg:
- sg-06308bff25b03fe2c
elb-tcp-sg:
- sg-099e88f7bdd7b9fe4
