---
sys-domain: sys.sandbox.cps-prft.com
app-domain: apps.sandbox.cps-prft.com
mysql-monit-email: vkartheek.ky1311@gmail.com
credhub-user: admin
credhub-encrypt-key-user: admin
pas-network: pcf-pas
az-configuration:
- name: us-east-1a
- name: us-east-1b
- name: us-east-1c
singleton-az: us-east-1a
credhub_internal_provider_key_name: sandboxcredhubtestkey
buildpack-bucket:
droplet-bucket:
package-bucket:
resource-bucket:
backup-buildpack-bucket:
backup-droplet-bucket:
backup-package-bucket:
