---
pivnet_token: ((pivnet_token))
platform_automation_version: 4.4.3
opsman_version: 2\.7\.6
git_private_key: ((git_keys.private_key))
git_uri: "git@github.com:kartikeyavadlapatla/pcf-poc.git"
git_branch: "master"
git_template_uri: "git@github.com:kartikeyavadlapatla/pcf-templates.git"
git_template_branch: "master"
foundation: "sandbox"
#pas_glob: cf*.pivotal
#pas_slug: elastic-runtime
pas_version: 2\.9\.(.*)
#####iaas: vsphere
stemcell_xenial_version: 621\.(.*)
stemcell_metrics_version: 170\.82
metrics_version: 2\.0\.(.*)
metrics_stemcell: "170.82"
xenial_stemcell: "456.74"
redis_version: 2\.3\.(.*)
redis_enterprise_version: 5\.4\.(.*)
mysqlv2_version: 2\.8\.(.*)
rabbitmq_version: 1\.19\.(.*)
spring_cloud_services_version: 3\.1\.(.*)
single_sign_on_version: 1\.12\.(.*)
health_watch_version: 1\.8\.(.*)
storage-backup-bucket: "tile-storage-bucket-bcbsma" 
storage-endpoint: "s3.us-east-1.amazonaws.com"
storage-access-key-id: ((s3-storage-access-key-id))
storage-secret-access-key: ((s3-storage-secret-access-key))
