---
pivnet_token: ((pivnet_token))
platform_automation_version: 3.0.1
opsman_version: 2\.7\.6
git_private_key: ((git_keys.private_key))
git_uri: ""
git_branch: "dev"
git_template_uri: ""
git_template_branch: "dev"
foundation: "sandbox"
pas_glob: cf*.pivotal
pas_slug: elastic-runtime
pas_version: 2\.7\.5
#####iaas: vsphere
stemcell_xenial_version: 97\.204
stemcell_metrics_version: 170\.82
metrics_version: 1\.6\.1
metrics_stemcell: "170.82"
xenial_stemcell: "456.74"
redis_version: 2\.2\.8
redis-enterprise_version: 5\.4\.40700169
mysqlv2_version: 2\.7\.2
rabbitmq_version: 1\.17\.4
spring-cloud-services_version: 3\.1\.3
single-sign-on_version: 1\.11\.0
storage-backup-bucket: tile-storage-bucket 
storage-endpoint: https://s3-us-east-1.amazonaws.com
storage-access-key-id: ((s3-storage-access-key-id))
storage-secret-access-key: ((s3-storage-secret-access-key))
